### ISSUE TITLE
Cannnot import cairo

### ISSUE THREAD

**Issue by kyeboah** [conda-forge/pycairo-feedstock#33]
I am unable to import cairo despite successfully installing pycairo

**Comment by ryanvolz** [comment]
Is there an error message or traceback associated with this failure to import? Is there anything potentially uncommon about your setup? The output of `conda list` could be useful. Importing `cairo` is one of the tests that it does after building, so it should work in general.

**Comment by stuarteberg** [comment]
@kyeboah It would also be good to know if you're using an Apple M1 machine...
